### PR TITLE
[WIP] Upgrade with ember-cli-update to latest

### LINKED ISSUE #4: update ember-cli-babel
The ember-cli-babel dependency should be updated to the latest version to allow consuming apps to drop ember-cli-shims as a dependency of ember 2.16+ apps.
https://www.emberjs.com/blog/2017/11/20/ember-2-17-released.html#toc_changes-in-ember-cli-2-17

### PR DESCRIPTION
**Pull request by sivakumar-kailasam**
Fixes #4 and #5

### CODE REVIEW

**Comment by elidupuis** [comment]
Any chance this will get merged in the near future?

**Comment by sivakumar-kailasam** [comment]
Sorry I haven't been able to finish up on this. Will try to wrap this up soon

**Comment by musaffa** [comment]
@sivakumar-kailasam Would be glad if it is merged and a new release is made soon.

**Comment by seansellek** [comment]
Is there anything I can do to help with this PR? What work is outstanding?

**Comment by jnlsn** [comment]
I'm happy to help move this forward as well. Let us know what you need!

**Comment by sivakumar-kailasam** [comment]
Thanks for reaching out🙂. 

As such i still need to add test cases & bring in a sample dummy app that we can use to preview the components within this repo. 

I'll spend sometime this week to sort this out. In case I don't resolve this, I'll update this PR with my progress so that folks can pitch in with PRs to help.

**Comment by jnlsn** [comment]
Any update on this?

**Comment by sivakumar-kailasam** [comment]
Unfortunately I couldn't finish off what's required to land this PR. I'm going to close this for now in case someone else wants to take a shot at it. 

Changes from this PR are available on the upgrade branch on this repo.

**Pull request closed without merging**
