### PR TITLE
update to 3.12

### PR DESCRIPTION
**Pull request by patrick-emmanuel**
Update to 3.12 before finally updating to Octane

### CODE REVIEW

**Review by rajasegar — APPROVED** [review]
Just out of curiosity @the-bionic you manually upgraded to 3.12, have you thought about using ember-cli-update

**Review by KamiKillertO — APPROVED** [review]

**Comment by patrick-emmanuel** [comment]
@rajasegar thanks for the review! Yes, I used `ember-cli-update` but I also had to manually update some tests to the use the `async` syntax, plus some imports.

**Comment by JamesWilmot** [comment]
Hi @the-bionic,
Any chance we could get this packaged up in a release?

**Comment by rajasegar** [comment]
@whastings @nathanhammond @MelSumner 
Please help

**Pull request merged**
